version: "3"
services:
    remix:
        container_name: remix
        build: ./docker/remix
        tty: true
        volumes:
            - ./frontend:/app
        command: sh -c "npm install && npm run dev"
        ports:
            - "3000:3000"
            - "3001:3001"

    go:
        container_name: go
        build: ./docker/go
        tty: true
        ports:
            - "8080:8080"
        depends_on:
            - db
        volumes:
            - ./backend/app:/go/src/app
        command: sh -c 'go mod tidy && GO_ENV=dev air && GO_ENV=dev go run main.go'
        networks:
            - golang_network

    db:
        container_name: db
        build: ./docker/mysql
        tty: true
        platform: linux/x86_64
        ports:
            - 3306:3306
        volumes:
            - mysql_volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_USER: ${ROOTUSER}
            MYSQL_ROOT_PASSWORD: ${ROOTPASS}
            MYSQL_DATABASE: ${DATABASE}
            MYSQL_USER: ${USERNAME}
            MYSQL_PASSWORD: ${USERPASS}
            TZ: "Asia/Tokyo"
        env_file:
            - .env
        networks:
            - golang_network

volumes:
    mysql_volume:
        name: mysql_volume

networks:
    golang_network:
        external: true